Parameters:
  KeyName:
    Default: main
    Description: Name of an existing EC2 KeyPair to enable SSH access to the instance
    Type: String
Resources:
  PortfolioHost:
    Properties:
      ImageId: ami-0afcbcee3dfbce929
      InstanceType: t3.nano
      KeyName: !Ref 'KeyName'
      SecurityGroups:
        - !Ref 'SSHSecurityGroup'
    Type: AWS::EC2::Instance
  SSHSecurityGroup:
    Properties:
      GroupDescription: Allow SSH access from my Turkey IP
      SecurityGroupIngress:
        - CidrIp: 185.117.123.142/32
          FromPort: '22'
          IpProtocol: tcp
          ToPort: '22'
    Type: AWS::EC2::SecurityGroup

