Parameters:
  KeyName:
    Default: main
    Description: Name of an existing EC2 KeyPair to enable SSH access to the instance
    Type: String
Resources:
  AL2023SecurityGroup:
    Properties:
      GroupDescription: Allow SSH access from my Turkey IP
      SecurityGroupIngress:
        - CidrIp: 185.117.123.142/32
          FromPort: '22'
          IpProtocol: tcp
          ToPort: '22'
        - CidrIp: 185.117.123.142/32
          FromPort: 80
          IpProtocol: tcp
          ToPort: 80
    Type: AWS::EC2::SecurityGroup
  JenkinsHost:
    Properties:
      ImageId: ami-03484a09b43a06725
      InstanceType: t3.nano
      KeyName: !Ref 'KeyName'
      SecurityGroups:
        - !Ref 'AL2023SecurityGroup'
    Type: AWS::EC2::Instance

