Parameters:
  KeyName:
    Default: main
    Description: Name of an existing EC2 KeyPair to enable SSH access to the instance
    Type: String
Resources:
  AmazonLinuxSecurityGroup:
    Properties:
      GroupDescription: Allow SSH access from my Vantaa IP
      SecurityGroupIngress:
        - CidrIp: 176.72.100.93/32
          FromPort: '22'
          IpProtocol: tcp
          ToPort: '22'
        - CidrIp: '0.0.0.0/0'
          FromPort: 80
          IpProtocol: tcp
          ToPort: 80
    Type: AWS::EC2::SecurityGroup
  WhereToLiveHost:
    Properties:
      ImageId: ami-0d3a2960fcac852bc
      InstanceType: t3.nano
      KeyName: !Ref 'KeyName'
      SecurityGroups:
        - !Ref 'AmazonLinuxSecurityGroup'
    Type: AWS::EC2::Instance

